# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel:
        build:
            context: ./runtimes/php7.4-ubi8
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-7.4-ubi8/app
        ports:
            - '${APP_PORT:-8080}:8080'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            ADAPTER: apc
        volumes:
            - '.:/opt/app-root/src/'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}:root'
            MYSQL_DATABASE: '${DB_DATABASE}:laravel'
            MYSQL_USER: '${DB_USERNAME}:admin'
            MYSQL_PASSWORD: '${DB_PASSWORD}:admin'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - './sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
          retries: 3
          timeout: 5s
    #grafana:
    #    build:
    #        context: ./runtimes/grafana
    #        dockerfile: Dockerfile
    #    image: 'grafana'
    #    ports:
    #        - '${FORWARD_GRAFANA_PORT:-3000}:3000'
    #    volumes:
    #        - './grafana-data:/var/lib/grafana'
    #    networks:
    #        - sail
    #    depends_on:
    #        - laravel
    #influxdb:
    #    build:
    #        context: ./runtimes/influxdb
    #        dockerfile: Dockerfile
    #    image: 'influxdb'
    #    ports:
    #        - '${FORWARD_INFLUXDB_PORT:-8086}:8086'
    #    volumes:
    #        - './influxdbv2:/var/lib/influxdb2'
    #    networks:
    #        - sail
    #    depends_on:
    #        - grafana
    #telegraf:
    #    image: 'telegraf'
    #    volumes:
    #        - './runtimes/telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf'
    #    networks:
    #        - sail
    #    depends_on:
    #        - influxdb
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
