{
 "title": "aplicacao",
 "description": "Andre Amorim",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1s,5s,10s,15s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "host",
    "label": "host",
    "query": "SHOW TAG VALUES FROM \"phpfpm\" WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "Parametro 1",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_pool - $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pool" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "phpfpm",
     "query": "from(bucket: \"acme-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"app_parametro1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "accepted_conn" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "conn" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Parametro 2",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_pool - $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pool" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "phpfpm",
     "query": "from(bucket: \"acme-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"app_parametro2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "active_processes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "active" ], "type": "alias" }
      ],
      [
       { "params": [ "idle_processes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "idle" ], "type": "alias" }
      ],
      [
       { "params": [ "max_active_processes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "max_active" ], "type": "alias" }
      ],
      [
       { "params": [ "total_processes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Parametro 5",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_pool - $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pool" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "phpfpm",
     "query": "from(bucket: \"acme-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"app_parametro5\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "slow_requests" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "conn" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Parametro 4",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_pool - $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pool" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "phpfpm",
     "query": "from(bucket: \"acme-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"app_parametro4\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "max_children_reached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Parametro 3",
   "type": "graph",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_pool - $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pool" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "phpfpm",
     "query": "from(bucket: \"acme-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"app_parametro3\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gauge\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "listen_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "count" ], "type": "alias" }
      ],
      [
       { "params": [ "listen_queue_len" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "length" ], "type": "alias" }
      ],
      [
       { "params": [ "max_listen_queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}